FROM node:20-alpine

WORKDIR /app

RUN npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-timeout 300000


COPY package*.json ./
RUN npm install

EXPOSE 5172

CMD ["npm", "run", "dev", "--", "--host"]